# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: v0.2.0-7-g2595516
_src_path: .
default_builder: html
default_language: en
html_baseurl: https://documatt.com/sphinx-doc-template
html_theme: alabaster
license: MIT
other_builders: []
other_languages: []
project_author: Documatt.com, s.r.o.
project_name: Sphinx Documentation Template
project_slug: docs
project_version: 0.1.0
